#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Traefik / hostname settings
config["host"] = os.getenv("TRAEFIK_HOST", "")
config["lets_encrypt"] = agent.get_route(os.environ['MODULE_ID']).get('lets_encrypt', False)

# JVM heap size
config["java_heap_mb"] = int(os.getenv("JAVA_HEAP_MB", 1024))

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
