#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

declare -A passwords
while IFS='=' read -r key value; do
    passwords[$key]=$value
done < "${AGENT_STATE_DIR}/passwords.env"

DB_ROOT_PASSWORD=${passwords[DB_ROOT_PASSWORD]}
DB_PASSWORD=${passwords[DB_PASSWORD]}

if [ -z "${DB_ROOT_PASSWORD}" ] || [ -z "${DB_PASSWORD}" ]; then
    echo "Missing DB_ROOT_PASSWORD or DB_PASSWORD in ${AGENT_STATE_DIR}/passwords.env" >&2
    exit 1
fi

# Prepare an initialization script that restores the dump file
mkdir -vp initdb.d
mv -v xwiki.sql initdb.d
#do the bash file to restore and exit once done
cat - >initdb.d/zz_xwiki_restore.sh <<'EOS'
# Print additional information:
mariadb --version
# The script is sourced, override entrypoint args and exit:
set -- true
docker_temp_server_stop
exit 0
EOS

# once we exit we remove initdb.d
trap 'rm -fv initdb.d/xwiki.sql initdb.d/zz_xwiki_restore.sh' EXIT

# we start a container to initiate a database and load the dump
# at the end of xwiki_restore.sh the dump is loaded and 
# we exit the container
podman run \
  --rm \
  --interactive \
  --network=none \
  --volume=./initdb.d:/docker-entrypoint-initdb.d:z \
  --volume mysql-data:/var/lib/mysql/:Z \
  --env MARIADB_ROOT_PASSWORD="${DB_ROOT_PASSWORD}" \
  --env MARIADB_DATABASE=xwiki \
  --env MARIADB_USER=xwiki \
  --env MARIADB_PASSWORD="${DB_PASSWORD}" \
  --replace --name=restore_db \
  ${MARIADB_IMAGE}
